serverAddr = "82.156.242.74"
serverPort = 7000

[[proxies]]
name = "NormalRunner"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
remotePort = 9998

[[proxies]]
name = "CMDRunner"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9090
remotePort = 9999
